---
name: Bug Report 🐛
description: Create a bug report for pnpm
labels: ['type: bug']
body:
  - type: checkboxes
    attributes:
      label: Verify latest release
      description: 'Please run `pnpm install -g pnpm@latest` to try the latest version of pnpm. Some issues may already be fixed in the latest release, so please verify that your issue reproduces before opening a new issue.'
      options:
        - label: I verified that the issue exists in the latest pnpm release (Or the latest version of my major)
          required: true
  - type: dropdown
    attributes:
      label: Which area(s) of pnpm are affected? (leave empty if unsure)
      multiple: true
      options:
        - 'Dependencies resolver'
        - 'CLI'
        - 'Lockfile'
        - 'Store'
        - 'Package manager compatibility'
        - 'Operating System (Windows, MacOS, Linux)'
        - 'Hooks'
  - type: input
    attributes:
      label: Link to the code that reproduces this issue or a replay of the bug
      description: |
        A link to a GitHub repository minimal reproduction. If a minimal reproduction can't be created please share a replay of the bug which doesn't require sharing a private repo.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
    validations:
      required: true
  - type: markdown
    attributes:
      value: ----------------------------
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    attributes:
      value: ----------------------------
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: ----------------------------
  - type: input
    attributes:
      label: Which Node.js version are you using? (if relevant)
      description: 'Please specify the exact version. For example: 14.18.1'
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: What OS are you using?
      options:
        - MacOS
        - Windows
        - Linux based (Ubuntu, Debian, CentOS...)
    validations:
      required: true
  - type: input
    attributes:
      label: If your OS is a Linux based, which one it is? (Include the version if relevant)
      placeholder: Linux, Ubuntu, Debian...
